//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialOfCrusaders.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArchiveText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArchiveText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrialOfCrusaders.Resources.Text.ArchiveText", typeof(ArchiveText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say that the signs to shape destiny could take upon 10 different forms. The scream for help has seen almost as much stars shaped as the once that should follow. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_01 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say that there are some abilities one may acquire that help them in all future trials. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_02 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say one should take a look a this room once they defy all odds. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_03 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say that the crowd falls more for those which don&apos;t need divine powers to bolster their might. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_05 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say the nobles carved hidden paths into the destiny. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_06 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say that there are {0} different powers one may obtain. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_07 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say certain powers may prevent others from appearing altogether. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_08 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say the misguided arrows are a sign from the higher beings. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_09 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say that there are six different afflictions that can be casted upon enemies. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_10 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say that the watchers pity the unlucky in their desperate hour. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_24 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say that the one keeping track hides a cryptic message at certain points. Although only the bravest warrior may be able to see the whole picture. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_35 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say there is only one power which cannot appear under normal circumstances. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_36 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die They say the instrument to inspect what many try to hide not only serves as a weapon and gathering essences. ähnelt.
        /// </summary>
        internal static string BELIEVE_TAB_57 {
            get {
                return ResourceManager.GetString("BELIEVE_TAB_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One of the common folk. ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_01 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Domination of a higher being (or its servant) ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_02 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than 15000 ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_03 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Faster than 1 hour ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_05 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Glory, even to a heretic ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_06 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conquer the trial ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_07 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than 5000 ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_08 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than 20000 ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_09 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Affliction Master ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_10 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conquer the grand trial ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_24 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Friend of the Grubs ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_35 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More than 10000 ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_36 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collector of ones dreams ähnelt.
        /// </summary>
        internal static string Locked_BELIEVE_TAB_57 {
            get {
                return ResourceManager.GetString("Locked_BELIEVE_TAB_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The tablet is filled with many glyphs you can&apos;t decipher. But carved in the frame you can read the words &quot;{0}&quot;. ähnelt.
        /// </summary>
        internal static string LockedPrompt {
            get {
                return ResourceManager.GetString("LockedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The scream vanquished into the amount of different artifacts the relic seeker may accept. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_01 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is said, that there are 4 of these… ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_02 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If you are reading this, you&apos;ve proven not only your might with the nail. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_03 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The crowd especially falls for gladiators which took upon the burden of pain. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_05 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are 6 bequest send out by the nobles. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_06 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of which are common, {1} are uncommon and {2} are rare. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_07 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Despite the similarities it might resemble, &quot;Void Heart&quot; is not exiled while being under &quot;Shining Bound&quot;. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_08 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The arrows may appear at certain crossroads, but that information is trying to deceive you. Their position at the crossroads however... ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_09 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Cull the Weak&quot; increases the duration of &quot;Root&quot;, the damage of &quot;Burn&quot; and &quot;Bleed&quot; and the power of &quot;Concussion&quot; and &quot;Weakened&quot;. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_10 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The gift shall lapse if one chooses any of the highest rank. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_24 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4, 13, 25, 41, 57, 70, 82, 99 ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_35 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ones that kill their foes unscarred may succumb the tempation of said power… ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_36 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The lingering dreams left in the kingdom may open new paths. ähnelt.
        /// </summary>
        internal static string Secret_BELIEVE_TAB_57 {
            get {
                return ResourceManager.GetString("Secret_BELIEVE_TAB_57", resourceCulture);
            }
        }
    }
}
