//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialOfCrusaders.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PowerDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerDescriptions() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrialOfCrusaders.Resources.Text.PowerDescriptions", typeof(PowerDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Abyss Shriek. ähnelt.
        /// </summary>
        internal static string AbyssShriek {
            get {
                return ResourceManager.GetString("AbyssShriek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemies deal less damage. Hazards now kill you instantly. ähnelt.
        /// </summary>
        internal static string AchillesHeel {
            get {
                return ResourceManager.GetString("AchillesHeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A nail hit right after dashing does increased damage and ignores armor. ähnelt.
        /// </summary>
        internal static string Acrobat {
            get {
                return ResourceManager.GetString("Acrobat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grants a shield while focusing. ähnelt.
        /// </summary>
        internal static string BaldurShell {
            get {
                return ResourceManager.GetString("BaldurShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holding the quick map button for 5 seconds will PERMANENTLY remove the current room from the room selection. Can only be used once per run. Trying to banish a room while another is already banished will replace it instead. ähnelt.
        /// </summary>
        internal static string Banish {
            get {
                return ResourceManager.GetString("Banish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hitting an enemy with the dream nail can root them shortly. ähnelt.
        /// </summary>
        internal static string BindingCircle {
            get {
                return ResourceManager.GetString("BindingCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nail arts ignore armor. ähnelt.
        /// </summary>
        internal static string BrutalStrikes {
            get {
                return ResourceManager.GetString("BrutalStrikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spells deal increased damage, but each cast lowers spell damage for the rest of the room. ähnelt.
        /// </summary>
        internal static string BurstingSoul {
            get {
                return ResourceManager.GetString("BurstingSoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excessive soul may manifest in a soul sphere. Touching it will grant all stored soul. Only one sphere can be active at a time. ähnelt.
        /// </summary>
        internal static string Caching {
            get {
                return ResourceManager.GetString("Caching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While at full health, slowly regenerates soul. ähnelt.
        /// </summary>
        internal static string CalmMind {
            get {
                return ResourceManager.GetString("CalmMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occasionally blocks damage. Doesn&apos;t work against instant kill damage. ähnelt.
        /// </summary>
        internal static string CarefreeMelody {
            get {
                return ResourceManager.GetString("CarefreeMelody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hazards deal less damage. ähnelt.
        /// </summary>
        internal static string CaringShell {
            get {
                return ResourceManager.GetString("CaringShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You move and attack faster shortly after entering the room. ähnelt.
        /// </summary>
        internal static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prevents lethal hits... sometimes. Can only occur once per 10 cleared rooms. Does not work on instant kill effects. ähnelt.
        /// </summary>
        internal static string CheatDeath {
            get {
                return ResourceManager.GetString("CheatDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grants 6 lifeblood. This power is in all draft pools. ähnelt.
        /// </summary>
        internal static string Cocoon {
            get {
                return ResourceManager.GetString("Cocoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status effects are stronger. Doesn&apos;t apply to shattered mind. ähnelt.
        /// </summary>
        internal static string CullTheWeak {
            get {
                return ResourceManager.GetString("CullTheWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Cyclone Slash. ähnelt.
        /// </summary>
        internal static string CycloneSlash {
            get {
                return ResourceManager.GetString("CycloneSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases the chance of treasure room significantly. After taking damage the first time, each second could be your last... ähnelt.
        /// </summary>
        internal static string Damocles {
            get {
                return ResourceManager.GetString("Damocles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decreases the dash cooldown. Allows dashing downwards. ähnelt.
        /// </summary>
        internal static string Dashmaster {
            get {
                return ResourceManager.GetString("Dashmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Dash Slash. ähnelt.
        /// </summary>
        internal static string DashSlash {
            get {
                return ResourceManager.GetString("DashSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entering a new room restores a bit of soul. Gained amount decreases with missing health. ähnelt.
        /// </summary>
        internal static string DeepBreath {
            get {
                return ResourceManager.GetString("DeepBreath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nail hits may apply bleed. ähnelt.
        /// </summary>
        internal static string DeepCuts {
            get {
                return ResourceManager.GetString("DeepCuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus is slower, but restores two health. ähnelt.
        /// </summary>
        internal static string DeepFocus {
            get {
                return ResourceManager.GetString("DeepFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emits a poison cloud. ähnelt.
        /// </summary>
        internal static string DefendersCrest {
            get {
                return ResourceManager.GetString("DefendersCrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Descending Dark. ähnelt.
        /// </summary>
        internal static string DescendingDark {
            get {
                return ResourceManager.GetString("DescendingDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Desolate Dive. ähnelt.
        /// </summary>
        internal static string DesolateDive {
            get {
                return ResourceManager.GetString("DesolateDive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus speed increases with missing health. ähnelt.
        /// </summary>
        internal static string Desperation {
            get {
                return ResourceManager.GetString("Desperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shops prices are reduced by 30%. ähnelt.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks the dream nail to gather soul from hit foes. ähnelt.
        /// </summary>
        internal static string DreamNail {
            get {
                return ResourceManager.GetString("DreamNail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holding the quick map button spawns a portal. Quickly pressing same button teleports you the location. 15 seconds cooldown. May not work in rooms with an arena. ähnelt.
        /// </summary>
        internal static string DreamPortal {
            get {
                return ResourceManager.GetString("DreamPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spawns a rotating shield around you. ähnelt.
        /// </summary>
        internal static string DreamShield {
            get {
                return ResourceManager.GetString("DreamShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dream Nail can be casted while moving. ähnelt.
        /// </summary>
        internal static string DreamWalker {
            get {
                return ResourceManager.GetString("DreamWalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases dream nail power and speed. ähnelt.
        /// </summary>
        internal static string DreamWielder {
            get {
                return ResourceManager.GetString("DreamWielder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Howling Wraiths/Abyss Shriek may trigger multiple times. ähnelt.
        /// </summary>
        internal static string EchoingScream {
            get {
                return ResourceManager.GetString("EchoingScream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases your movement speed while recovering from a hit. ähnelt.
        /// </summary>
        internal static string EscapeArtist {
            get {
                return ResourceManager.GetString("EscapeArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After standing still for 5 second you no longer take damage. Breaks on any action. ähnelt.
        /// </summary>
        internal static string Fade {
            get {
                return ResourceManager.GetString("Fade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geo is 200% more worth. No longer works upon taking damage. ähnelt.
        /// </summary>
        internal static string FragileGreed {
            get {
                return ResourceManager.GetString("FragileGreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All spells cause burn. No longer works upon taking damage. ähnelt.
        /// </summary>
        internal static string FragileSpirit {
            get {
                return ResourceManager.GetString("FragileSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nail damage is increased by 300%. No longer works upon taking damage. ähnelt.
        /// </summary>
        internal static string FragileStrength {
            get {
                return ResourceManager.GetString("FragileStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While at 1 health, increase nail damage significantly. ähnelt.
        /// </summary>
        internal static string FuryOfTheFallen {
            get {
                return ResourceManager.GetString("FuryOfTheFallen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pulls nearby geo towards you. ähnelt.
        /// </summary>
        internal static string GatheringSwarm {
            get {
                return ResourceManager.GetString("GatheringSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Periodically spawns a hatchling that attacks enemies. Consumes Soul. ähnelt.
        /// </summary>
        internal static string GlowingWomb {
            get {
                return ResourceManager.GetString("GlowingWomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spending soul has a chance to spawn an temporary rotating orb at your location that deals damage. ähnelt.
        /// </summary>
        internal static string GreaterMind {
            get {
                return ResourceManager.GetString("GreaterMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Great Slash. ähnelt.
        /// </summary>
        internal static string GreatSlash {
            get {
                return ResourceManager.GetString("GreatSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases the geo dropped from enemies. ähnelt.
        /// </summary>
        internal static string Greed {
            get {
                return ResourceManager.GetString("Greed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summons a companion that attacks enemies. ähnelt.
        /// </summary>
        internal static string Grimmchild {
            get {
                return ResourceManager.GetString("Grimmchild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A hardfall emits shockwaves that damage enemies hit. ähnelt.
        /// </summary>
        internal static string GroundSlam {
            get {
                return ResourceManager.GetString("GroundSlam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While at full health fire waves with your nail. ähnelt.
        /// </summary>
        internal static string GrubberflysElegy {
            get {
                return ResourceManager.GetString("GrubberflysElegy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taking a hit restores soul. ähnelt.
        /// </summary>
        internal static string Grubsong {
            get {
                return ResourceManager.GetString("Grubsong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases knockback from hitting enemies. ähnelt.
        /// </summary>
        internal static string HeavyBlow {
            get {
                return ResourceManager.GetString("HeavyBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taking damage regenerates the last mask lost. ähnelt.
        /// </summary>
        internal static string Hiveblood {
            get {
                return ResourceManager.GetString("Hiveblood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases nail damage for each consecutive nail hit. Failing to hit an enemy resets the counter. ähnelt.
        /// </summary>
        internal static string HotStreak {
            get {
                return ResourceManager.GetString("HotStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Howling Wraiths. ähnelt.
        /// </summary>
        internal static string HowlingWraiths {
            get {
                return ResourceManager.GetString("HowlingWraiths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases hitpoints and regenerates over time. ähnelt.
        /// </summary>
        internal static string ImprovedBaldursShell {
            get {
                return ResourceManager.GetString("ImprovedBaldursShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avoids damage more often. ähnelt.
        /// </summary>
        internal static string ImprovedCarefreeMelody {
            get {
                return ResourceManager.GetString("ImprovedCarefreeMelody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decreases hazard damage even further. Hazards do not deal damage in calm rooms anymore. ähnelt.
        /// </summary>
        internal static string ImprovedCaringShell {
            get {
                return ResourceManager.GetString("ImprovedCaringShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage is increased. Grants invincibility upon start. Invinciblity has a cooldown. ähnelt.
        /// </summary>
        internal static string ImprovedCrystalDash {
            get {
                return ResourceManager.GetString("ImprovedCrystalDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemies hit by the cloud become weakened. ähnelt.
        /// </summary>
        internal static string ImprovedDefendersCrest {
            get {
                return ResourceManager.GetString("ImprovedDefendersCrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus now consumes all soul energy to grant all masks immediately. ähnelt.
        /// </summary>
        internal static string ImprovedFocus {
            get {
                return ResourceManager.GetString("ImprovedFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The fury threshold is increased. ähnelt.
        /// </summary>
        internal static string ImprovedFuryOfTheFallen {
            get {
                return ResourceManager.GetString("ImprovedFuryOfTheFallen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gathers geo more efficient. While not in combat, slowly moves orbs towards you. ähnelt.
        /// </summary>
        internal static string ImprovedGatheringSwarm {
            get {
                return ResourceManager.GetString("ImprovedGatheringSwarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hatchlings cost way less soul. Damage and spawn rate is increased. ähnelt.
        /// </summary>
        internal static string ImprovedGlowingWomb {
            get {
                return ResourceManager.GetString("ImprovedGlowingWomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scarlet energy flows through the Grimmchild increasing its power. ähnelt.
        /// </summary>
        internal static string ImprovedGrimmchild {
            get {
                return ResourceManager.GetString("ImprovedGrimmchild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adds a chance to cause a concussion on enemies. ähnelt.
        /// </summary>
        internal static string ImprovedHeavyBlow {
            get {
                return ResourceManager.GetString("ImprovedHeavyBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regeneration speed is increased. ähnelt.
        /// </summary>
        internal static string ImprovedHiveblood {
            get {
                return ResourceManager.GetString("ImprovedHiveblood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemies hit by the wings are damaged. Has a chance to apply bleed or concussion. ähnelt.
        /// </summary>
        internal static string ImprovedMonarchWings {
            get {
                return ResourceManager.GetString("ImprovedMonarchWings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kills restore health. ähnelt.
        /// </summary>
        internal static string ImprovedSharpShadow {
            get {
                return ResourceManager.GetString("ImprovedSharpShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reduces spell cost even further. ähnelt.
        /// </summary>
        internal static string ImprovedSpellTwister {
            get {
                return ResourceManager.GetString("ImprovedSpellTwister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates spore clouds on its own. ähnelt.
        /// </summary>
        internal static string ImprovedSporeshroom {
            get {
                return ResourceManager.GetString("ImprovedSporeshroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grants a significant speed boost. ähnelt.
        /// </summary>
        internal static string ImprovedSprintmaster {
            get {
                return ResourceManager.GetString("ImprovedSprintmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extends the invincibility after getting hit. ähnelt.
        /// </summary>
        internal static string ImprovedStalwartShell {
            get {
                return ResourceManager.GetString("ImprovedStalwartShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leeches soul from enemies hit. Improves agility. ähnelt.
        /// </summary>
        internal static string ImprovedThornsOfAgony {
            get {
                return ResourceManager.GetString("ImprovedThornsOfAgony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases weaver size. Damage now scales. ähnelt.
        /// </summary>
        internal static string ImprovedWeaversong {
            get {
                return ResourceManager.GetString("ImprovedWeaversong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first hit on enemies deals bonus damage and grants extra soul. ähnelt.
        /// </summary>
        internal static string Initiative {
            get {
                return ResourceManager.GetString("Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geo value is slightly increased. ähnelt.
        /// </summary>
        internal static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entering a room applies weakened to all enemies. ähnelt.
        /// </summary>
        internal static string IntimidatingShout {
            get {
                return ResourceManager.GetString("IntimidatingShout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fully heals you. You can no longer heal. Focus now spawns a shade which afflicts debuffs. ähnelt.
        /// </summary>
        internal static string InUtterDarkness {
            get {
                return ResourceManager.GetString("InUtterDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slowly generates soul. ähnelt.
        /// </summary>
        internal static string Kingsoul {
            get {
                return ResourceManager.GetString("Kingsoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases the range of your nail. ähnelt.
        /// </summary>
        internal static string Longnail {
            get {
                return ResourceManager.GetString("Longnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases the chance of obtaining bonus stats from abilities. ähnelt.
        /// </summary>
        internal static string LuckyCharm {
            get {
                return ResourceManager.GetString("LuckyCharm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An attack after a parry does increased damage. ähnelt.
        /// </summary>
        internal static string MantisStyle {
            get {
                return ResourceManager.GetString("MantisStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases the nail range significantly. Overwrites Longnail. ähnelt.
        /// </summary>
        internal static string MarkOfPride {
            get {
                return ResourceManager.GetString("MarkOfPride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Each time you pick an uncommon power, there is a chance that an endurance orb will spawn. The chance increases for each uncommon power you pick in a row. ähnelt.
        /// </summary>
        internal static string Mediocracy {
            get {
                return ResourceManager.GetString("Mediocracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attacks in the same direction within half a second grant stacking attack speed. ähnelt.
        /// </summary>
        internal static string MercilessPursuit {
            get {
                return ResourceManager.GetString("MercilessPursuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dream nail applies shattered mind. ähnelt.
        /// </summary>
        internal static string Mindblast {
            get {
                return ResourceManager.GetString("Mindblast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decreases the charge time of nail arts. ähnelt.
        /// </summary>
        internal static string NailmastersGlory {
            get {
                return ResourceManager.GetString("NailmastersGlory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clearing a room without casting a spell/using focus has a small chance to spawn a combat orb. ähnelt.
        /// </summary>
        internal static string NailProdigy {
            get {
                return ResourceManager.GetString("NailProdigy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first hit in each room is ignored. Doesn&apos;t block instant death effects. ähnelt.
        /// </summary>
        internal static string PaleShell {
            get {
                return ResourceManager.GetString("PaleShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For each room you succeeded hitless the amount of geo enemies drop increases. ähnelt.
        /// </summary>
        internal static string Perfection {
            get {
                return ResourceManager.GetString("Perfection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cast spells are sometimes the opposite level. ähnelt.
        /// </summary>
        internal static string PolarityShift {
            get {
                return ResourceManager.GetString("PolarityShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vengeful Spirit has a chance to ignite hit enemies causing burn. ähnelt.
        /// </summary>
        internal static string Pyroblast {
            get {
                return ResourceManager.GetString("Pyroblast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase focus speed. ähnelt.
        /// </summary>
        internal static string QuickFocus {
            get {
                return ResourceManager.GetString("QuickFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases attack speed. ähnelt.
        /// </summary>
        internal static string QuickSlash {
            get {
                return ResourceManager.GetString("QuickSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Great Slash and Dash Slash deal 400% increased damage, but you take damage if this doesn&apos;t kill the enemy. ähnelt.
        /// </summary>
        internal static string Recklessness {
            get {
                return ResourceManager.GetString("Recklessness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Powers are more common in shops, but ALL shop prices are increased by 50%. ähnelt.
        /// </summary>
        internal static string RelicSeeker {
            get {
                return ResourceManager.GetString("RelicSeeker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killing an enemy that dealt damage to you recently restores a bit of health. ähnelt.
        /// </summary>
        internal static string Revenge {
            get {
                return ResourceManager.GetString("Revenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killing all enemies in the marked order will award bonus geo and sometimes power orbs. ähnelt.
        /// </summary>
        internal static string RoyalDecree {
            get {
                return ResourceManager.GetString("RoyalDecree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desolate Dive ignites the ground. Enemies within it take burn damage. ähnelt.
        /// </summary>
        internal static string ScorchingGround {
            get {
                return ResourceManager.GetString("ScorchingGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clearing a room without taking damage sometimes grants lifeblood. ähnelt.
        /// </summary>
        internal static string SeethingLifeblood {
            get {
                return ResourceManager.GetString("SeethingLifeblood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Shade Soul. ähnelt.
        /// </summary>
        internal static string ShadeSoul {
            get {
                return ResourceManager.GetString("ShadeSoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empowers all spells. ähnelt.
        /// </summary>
        internal static string ShamanStone {
            get {
                return ResourceManager.GetString("ShamanStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus can be casted while moving on the ground. ähnelt.
        /// </summary>
        internal static string ShapeOfUnn {
            get {
                return ResourceManager.GetString("ShapeOfUnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your shade dash is extended and deals damage. ähnelt.
        /// </summary>
        internal static string SharpShadow {
            get {
                return ResourceManager.GetString("SharpShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Consecutive hits onto the same target reduce the armor. ähnelt.
        /// </summary>
        internal static string Shatter {
            get {
                return ResourceManager.GetString("Shatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Halves all damage taken. You can no longer obtain charms. ähnelt.
        /// </summary>
        internal static string ShiningBound {
            get {
                return ResourceManager.GetString("ShiningBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slightly increases the soul gained from enemies. ähnelt.
        /// </summary>
        internal static string SoulCatcher {
            get {
                return ResourceManager.GetString("SoulCatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus and spells sometimes refund soul spend. ähnelt.
        /// </summary>
        internal static string SoulConserver {
            get {
                return ResourceManager.GetString("SoulConserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases soul gain by hitting enemies significantly. Overwrites Soul Catcher. ähnelt.
        /// </summary>
        internal static string SoulEater {
            get {
                return ResourceManager.GetString("SoulEater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clearing a room without the nail has a chance to grant a spirit orb. ähnelt.
        /// </summary>
        internal static string SpellProdigy {
            get {
                return ResourceManager.GetString("SpellProdigy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decreases the cost of spells. ähnelt.
        /// </summary>
        internal static string SpellTwister {
            get {
                return ResourceManager.GetString("SpellTwister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus emits a spore cloud. ähnelt.
        /// </summary>
        internal static string Sporeshroom {
            get {
                return ResourceManager.GetString("Sporeshroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases movement speed on the ground. ähnelt.
        /// </summary>
        internal static string Sprintmaster {
            get {
                return ResourceManager.GetString("Sprintmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases invicibilty after being hit. ähnelt.
        /// </summary>
        internal static string StalwartShell {
            get {
                return ResourceManager.GetString("StalwartShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removes the nail knockback. ähnelt.
        /// </summary>
        internal static string SteadyBody {
            get {
                return ResourceManager.GetString("SteadyBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decreases damage taken slightly. ähnelt.
        /// </summary>
        internal static string Sturdy {
            get {
                return ResourceManager.GetString("Sturdy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killing multiple enemies in a row without taking damage restores health. Can only occur once per room. ähnelt.
        /// </summary>
        internal static string Supreme {
            get {
                return ResourceManager.GetString("Supreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting hit let thorns attack nearby enemies. ähnelt.
        /// </summary>
        internal static string ThornsOfAgony {
            get {
                return ResourceManager.GetString("ThornsOfAgony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases the chance of finding a treasure room. ähnelt.
        /// </summary>
        internal static string TreasureHunter {
            get {
                return ResourceManager.GetString("TreasureHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Killing an enemy grants short invincibility. ähnelt.
        /// </summary>
        internal static string Vanish {
            get {
                return ResourceManager.GetString("Vanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlocks Vengeful Spirit. ähnelt.
        /// </summary>
        internal static string VengefulSpirit {
            get {
                return ResourceManager.GetString("VengefulSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The first nail hit after casting a spell grants bonus soul. ähnelt.
        /// </summary>
        internal static string Versatility {
            get {
                return ResourceManager.GetString("Versatility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die While in combat, points to the nearest required enemy. ähnelt.
        /// </summary>
        internal static string WaywardCompass {
            get {
                return ResourceManager.GetString("WaywardCompass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemies hit by spells are sometimes inflicted with shattered mind. ähnelt.
        /// </summary>
        internal static string WeakenedHusk {
            get {
                return ResourceManager.GetString("WeakenedHusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spawns weavers that assist you in battle. ähnelt.
        /// </summary>
        internal static string Weaversong {
            get {
                return ResourceManager.GetString("Weaversong", resourceCulture);
            }
        }
    }
}
