//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialOfCrusaders.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShopText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShopText() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrialOfCrusaders.Resources.Text.ShopText", typeof(ShopText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restores {0} masks. Each time you consume an egg, this healing effect will be weaker for the rest of this trial. ähnelt.
        /// </summary>
        internal static string Consumable_Egg_Desc {
            get {
                return ResourceManager.GetString("Consumable_Egg_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delicious Egg ähnelt.
        /// </summary>
        internal static string Consumable_Egg_Title {
            get {
                return ResourceManager.GetString("Consumable_Egg_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grants {0} lifeblood. For the rest of the runs further lifeblood badges grant additional lifeblood. ähnelt.
        /// </summary>
        internal static string Consumable_Lifeblood_Desc {
            get {
                return ResourceManager.GetString("Consumable_Lifeblood_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lifeblood Badge ähnelt.
        /// </summary>
        internal static string Consumable_Lifeblood_Title {
            get {
                return ResourceManager.GetString("Consumable_Lifeblood_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase your nail damage by 10 for the next 50 strikes (regardless of if they hit anything). Further consumptions will increase the left strikes by 25. ähnelt.
        /// </summary>
        internal static string Consumable_Nail_Desc {
            get {
                return ResourceManager.GetString("Consumable_Nail_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brittle Nail ähnelt.
        /// </summary>
        internal static string Consumable_Nail_Title {
            get {
                return ResourceManager.GetString("Consumable_Nail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows you to reroll a power selection. You can only use up to 2 seals per power selection. ähnelt.
        /// </summary>
        internal static string Consumable_Seal_Desc {
            get {
                return ResourceManager.GetString("Consumable_Seal_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Royal Seal ähnelt.
        /// </summary>
        internal static string Consumable_Seal_Title {
            get {
                return ResourceManager.GetString("Consumable_Seal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The next 5 spells you cast do not cost soul and their spirit scaling is doubled. Further consumptions increase the spell counter. ähnelt.
        /// </summary>
        internal static string Consumable_Tea_Desc {
            get {
                return ResourceManager.GetString("Consumable_Tea_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calming Tea ähnelt.
        /// </summary>
        internal static string Consumable_Tea_Title {
            get {
                return ResourceManager.GetString("Consumable_Tea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases your nail damage. Abilities marked with (C) scale with your combat level. ähnelt.
        /// </summary>
        internal static string Stat_Combat_Desc {
            get {
                return ResourceManager.GetString("Stat_Combat_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Combat Up ähnelt.
        /// </summary>
        internal static string Stat_Combat_Title {
            get {
                return ResourceManager.GetString("Stat_Combat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases your maximum and current health. Abilities marked with (E) scale with your endurance level. ähnelt.
        /// </summary>
        internal static string Stat_Endurance_Desc {
            get {
                return ResourceManager.GetString("Stat_Endurance_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endurance Up ähnelt.
        /// </summary>
        internal static string Stat_Endurance_Title {
            get {
                return ResourceManager.GetString("Stat_Endurance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increases the amount of soul you can have and receive. Also increases spell damage. Abilities marked with (S) scale with your spirit level. ähnelt.
        /// </summary>
        internal static string Stat_Spirit_Desc {
            get {
                return ResourceManager.GetString("Stat_Spirit_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spirit Up ähnelt.
        /// </summary>
        internal static string Stat_Spirit_Title {
            get {
                return ResourceManager.GetString("Stat_Spirit_Title", resourceCulture);
            }
        }
    }
}
